spring.application.name=evaluacion-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/uce_prueba
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


