spring.application.name=evaluacion-backend
<<<<<<< HEAD
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/uce_prueba
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
>>>>>>> 81d339fb64452be73656b41b9c3c78acdfe7c953
