name: Create Branch From Jira

on:
  repository_dispatch:
    types: [jira-ticket-created]

permissions:
  contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate branch name
        id: branch
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
          ISSUE_SUMMARY: ${{ github.event.client_payload.issue_summary }}
        run: |

          # Reemplazar espacios por guiones
          # y eliminar caracteres inválidos para Git
          CLEAN_SUMMARY=$(echo "$ISSUE_SUMMARY" \
            | sed 's/ /-/g' \
            | sed 's/[:?*~^]//g')

          # Formato estilo Jira
          BRANCH_NAME="$ISSUE_KEY-$CLEAN_SUMMARY"

          echo "Branch name:"
          echo "$BRANCH_NAME"

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Check if branch exists
        id: check_branch
        env:
          BRANCH_NAME: ${{ steps.branch.outputs.branch }}
        run: |

          if git ls-remote --heads origin "$BRANCH_NAME" | grep "$BRANCH_NAME"; then
            echo "Branch already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Branch does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch
        if: steps.check_branch.outputs.exists == 'false'
        env:
          BRANCH_NAME: ${{ steps.branch.outputs.branch }}
        run: |

          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Branch already exists
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          echo "Skipping branch creation because it already exists."
